import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Search,
  ChevronRight,
  Shield,
  Clock,
  DollarSign,
  Cloud,
  Layers,
  Lock,
  Eye,
  FileCheck,
} from "lucide-react";

export type CloudProvider = "aws" | "gcp" | "azure" | "oci";

export interface PreflightStep {
  id: string;
  name: string;
  description: string;
}

export interface GoldenPathEntry {
  id: string;
  intentId: string; // PRD: naawi.gold.v1.* taxonomy
  name: string;
  description: string;
  icon: string;
  providers: CloudProvider[];
  tier: "Foundation" | "Standard" | "Hardened" | "AI-Ops";
  sloAvailability: number;
  estimatedDeployMin: number;
  estimatedMonthlyCost: string;
  resources: Record<CloudProvider, string[]>;
  jitScope: string[];
  jitTtl: string; // per-layer TTL range
  rmcmThreshold: number; // minimum coherence score
  preflightSteps: PreflightStep[];
  doltTables: string[]; // Dolt schema tables written
  tags: string[];
  status: "v1.0 — Specification complete" | "v1.0 — Planned (Phase 2)" | "v1.0 — Planned (Phase 3)";
}

const PREFLIGHT_STANDARD: PreflightStep[] = [
  { id: "P-1", name: "Parameter Validation", description: "Server-side validation. CIDR overlap check against Dolt." },
  { id: "P-2", name: "Dolt State Read", description: "RMCM queries existing resources. Zero AWS API calls." },
  { id: "P-3", name: "RMCM Dependency Graph", description: "Per-layer coherence scores. Environment thresholds." },
  { id: "P-4", name: "JIT Credential Pre-check", description: "STS AssumeRole capability check. No credentials vended." },
  { id: "P-5", name: "Dry-Run (Shared Closure)", description: "Structured diff via Patent §4.8 shared closure." },
  { id: "P-6", name: "PREFLIGHT_COMPLETE", description: "Overall coherence, cost delta, JIT TTL. ZTAI record." },
];

const CATALOG: GoldenPathEntry[] = [
  {
    id: "vpc-foundation",
    intentId: "naawi.gold.v1.VpcFoundation",
    name: "VPC Foundation",
    description: "VPC + Subnets + IGW + NAT GW + Route Tables + SG. Multi-AZ, JIT per-layer credentials. The dependency root for all subsequent Golden Paths.",
    icon: "🌐",
    providers: ["aws", "gcp", "azure", "oci"],
    tier: "Foundation",
    sloAvailability: 99.99,
    estimatedDeployMin: 4,
    estimatedMonthlyCost: "$50–150",
    resources: {
      aws: ["VPC", "Subnets (×4)", "IGW", "NAT-GW", "Route Tables", "Security Group"],
      gcp: ["VPC Network", "Subnets", "Cloud NAT", "Cloud Router", "Firewall Rules"],
      azure: ["VNet", "Subnets", "NAT Gateway", "NSGs", "Route Tables"],
      oci: ["VCN", "Subnets (×4)", "IGW", "NAT Gateway", "Route Tables", "Security Lists"],
    },
    jitScope: ["ec2:CreateVpc", "ec2:CreateSubnet", "ec2:CreateNatGateway", "ec2:CreateSecurityGroup"],
    jitTtl: "1–5 min per layer",
    rmcmThreshold: 95,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "vpc_attrs", "subnet_attrs", "nat_gateway_attrs", "security_group_attrs", "route_table_attrs", "resource_raw", "ztai_refs"],
    tags: ["networking", "foundation", "multi-az", "layer-0"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "web-standard",
    intentId: "naawi.gold.v1.WebStandard",
    name: "Web Standard",
    description: "ALB + ECS Fargate + RDS Aurora Serverless v2. Auto-scaling compute with managed database.",
    icon: "🏗️",
    providers: ["aws", "gcp", "azure", "oci"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 12,
    estimatedMonthlyCost: "$300–2000",
    resources: {
      aws: ["VPC (dep)", "Subnets (×4)", "Security Group", "RDS Aurora Serverless v2", "ALB", "ECS Fargate"],
      gcp: ["Cloud LB", "Cloud Run", "Cloud SQL (HA)", "VPC (dep)"],
      azure: ["App Gateway", "Container Apps", "Azure SQL (HA)", "VNet (dep)"],
      oci: ["VCN (dep)", "Subnets (×4)", "NSG", "Autonomous DB", "Load Balancer", "Container Instances"],
    },
    jitScope: ["ecs:CreateService", "rds:CreateDBCluster", "elasticloadbalancing:CreateLoadBalancer"],
    jitTtl: "3–8 min per layer",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["web", "compute", "database", "standard"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "event-driven",
    intentId: "naawi.gold.v1.EventDriven",
    name: "Event-Driven Pipeline",
    description: "Lambda + SQS + DynamoDB. Serverless async with DLQ, retries, and exactly-once semantics.",
    icon: "📨",
    providers: ["aws", "gcp", "azure", "oci"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$20–500",
    resources: {
      aws: ["IAM Roles", "SQS", "DLQ", "DynamoDB", "EventBridge", "Lambda"],
      gcp: ["Pub/Sub", "Cloud Functions", "Firestore", "Eventarc", "DLQ"],
      azure: ["Service Bus", "Azure Functions", "Cosmos DB", "Event Grid", "DLQ"],
      oci: ["Dynamic Groups", "Queue", "DLQ", "NoSQL DB", "Events", "Functions"],
    },
    jitScope: ["sqs:CreateQueue", "lambda:CreateFunction", "dynamodb:CreateTable"],
    jitTtl: "2–5 min per layer",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["events", "async", "serverless", "pipeline"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "secure-edge",
    intentId: "naawi.gold.v1.SecureEdge",
    name: "Secure Edge",
    description: "CloudFront + WAF + Intent-based API Gateway. Global CDN with edge security and TLS.",
    icon: "🛡️",
    providers: ["aws", "gcp", "azure", "oci"],
    tier: "Hardened",
    sloAvailability: 99.95,
    estimatedDeployMin: 8,
    estimatedMonthlyCost: "$100–1000",
    resources: {
      aws: ["CloudFront", "WAF", "API Gateway", "ACM", "S3 Origin"],
      gcp: ["Cloud CDN", "Cloud Armor", "API Gateway", "SSL Cert", "GCS Origin"],
      azure: ["Front Door", "WAF Policy", "API Management", "App Service Cert"],
      oci: ["CDN", "WAF", "API Gateway", "Certificates", "Object Storage Origin"],
    },
    jitScope: ["cloudfront:CreateDistribution", "wafv2:CreateWebACL"],
    jitTtl: "3–6 min per layer",
    rmcmThreshold: 92,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["cdn", "waf", "edge", "security"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "container-platform",
    intentId: "naawi.gold.v1.ContainerPlatform",
    name: "Container Platform (K8s)",
    description: "Managed Kubernetes with node pools, IRSA/Workload Identity, and ingress controller.",
    icon: "🐳",
    providers: ["aws", "gcp", "azure", "oci"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 15,
    estimatedMonthlyCost: "$200–800",
    resources: {
      aws: ["VPC (dep)", "Subnets (×4)", "Security Group", "IAM Roles", "IRSA", "ALB", "EKS", "Node Groups", "ALB Ingress", "EBS CSI"],
      gcp: ["GKE", "Node Pools", "Ingress", "Workload Identity", "PD CSI"],
      azure: ["AKS", "Node Pools", "AGIC", "Managed Identity", "Disk CSI"],
      oci: ["VCN (dep)", "Subnets (×4)", "NSG", "Dynamic Groups", "OKE", "Node Pools", "LB Ingress", "Block Volume CSI"],
    },
    jitScope: ["eks:CreateCluster", "ec2:RunInstances", "iam:CreateRole"],
    jitTtl: "5–15 min per layer",
    rmcmThreshold: 88,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["kubernetes", "containers", "compute"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "serverless-api",
    intentId: "naawi.gold.v1.ServerlessApi",
    name: "Serverless API",
    description: "Functions + API Gateway + least-privilege IAM. Zero servers, auto-scaling by default.",
    icon: "⚡",
    providers: ["aws", "gcp", "azure", "oci"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 3,
    estimatedMonthlyCost: "$5–200",
    resources: {
      aws: ["Lambda", "API Gateway", "IAM Roles", "CloudWatch Logs"],
      gcp: ["Cloud Functions", "API Gateway", "IAM", "Cloud Logging"],
      azure: ["Azure Functions", "API Management", "Managed Identity", "App Insights"],
      oci: ["Functions", "API Gateway", "Dynamic Groups", "Logging"],
    },
    jitScope: ["lambda:CreateFunction", "apigateway:CreateRestApi"],
    jitTtl: "2–4 min per layer",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["serverless", "api", "functions"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "fintech-pci",
    intentId: "naawi.gold.v1.FintechPci",
    name: "Fintech / PCI-DSS",
    description: "Payment-grade infra: Vault integration, mTLS, zero-trust network, encryption everywhere.",
    icon: "🏦",
    providers: ["aws", "gcp", "azure", "oci"],
    tier: "Hardened",
    sloAvailability: 99.99,
    estimatedDeployMin: 20,
    estimatedMonthlyCost: "$1000–5000",
    resources: {
      aws: ["VPC (zero-trust)", "Subnets (×4)", "Security Group", "IAM Roles", "KMS", "Secrets Manager", "RDS", "EKS", "WAF"],
      gcp: ["GKE", "Cloud SQL", "Cloud KMS", "Secret Manager", "VPC-SC"],
      azure: ["AKS", "Azure SQL", "Key Vault", "VNet (zero-trust)", "WAF"],
      oci: ["OKE", "Autonomous DB", "Vault (KMS)", "Secrets", "VCN (zero-trust)", "WAF"],
    },
    jitScope: ["kms:CreateKey", "secretsmanager:CreateSecret"],
    jitTtl: "3–10 min per layer",
    rmcmThreshold: 98,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["compliance", "pci", "fintech", "zero-trust"],
    status: "v1.0 — Planned (Phase 3)",
  },
  {
    id: "service-mesh",
    intentId: "naawi.gold.v1.ServiceMesh",
    name: "Service Mesh",
    description: "Managed mesh with mTLS, circuit breakers, retries, and distributed tracing.",
    icon: "🕸️",
    providers: ["aws", "gcp", "azure", "oci"],
    tier: "Hardened",
    sloAvailability: 99.9,
    estimatedDeployMin: 15,
    estimatedMonthlyCost: "$400–3000",
    resources: {
      aws: ["VPC (dep)", "Subnets (×4)", "Security Group", "IAM Roles", "Cloud Map", "X-Ray", "ALB", "EKS", "App Mesh"],
      gcp: ["GKE", "Anthos Service Mesh", "Cloud Trace", "Cloud LB"],
      azure: ["AKS", "OSM / Istio", "App Insights", "App Gateway"],
      oci: ["OKE", "OCI Service Mesh", "APM", "Load Balancer"],
    },
    jitScope: ["appmesh:CreateMesh", "eks:UpdateClusterConfig"],
    jitTtl: "5–12 min per layer",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["mesh", "mtls", "observability", "microservices"],
    status: "v1.0 — Planned (Phase 3)",
  },
  {
    id: "ml-training",
    intentId: "naawi.gold.v1.MlTraining",
    name: "ML Training Pipeline",
    description: "GPU compute with spot/preemptible instances, checkpointing, and cost guardrails.",
    icon: "🧠",
    providers: ["aws", "gcp", "azure", "oci"],
    tier: "AI-Ops",
    sloAvailability: 95.0,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$500–10000",
    resources: {
      aws: ["VPC (dep)", "Subnets (×4)", "Security Group", "S3", "EBS", "EC2 (GPU)", "Spot Fleet", "CloudWatch GPU Metrics"],
      gcp: ["Compute (GPU)", "GCS", "Persistent Disk", "Vertex AI", "Preemptible VMs"],
      azure: ["NC-series VMs", "Blob Storage", "Managed Disks", "Azure ML", "Spot VMs"],
      oci: ["GPU Compute", "Object Storage", "Block Volumes", "Data Science", "Preemptible VMs"],
    },
    jitScope: ["ec2:RunInstances", "s3:CreateBucket"],
    jitTtl: "5–15 min per layer",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["ml", "gpu", "training", "ai"],
    status: "v1.0 — Planned (Phase 3)",
  },
  {
    id: "disaster-recovery",
    intentId: "naawi.gold.v1.DisasterRecovery",
    name: "Multi-Region DR",
    description: "Active-passive replication with automated failover, RTO < 15min, RPO < 1min.",
    icon: "🛡️",
    providers: ["aws", "gcp", "azure", "oci"],
    tier: "Hardened",
    sloAvailability: 99.999,
    estimatedDeployMin: 25,
    estimatedMonthlyCost: "$2000–10000",
    resources: {
      aws: ["VPC (dep)", "Subnets (×4)", "Security Group", "IAM Roles", "RDS Global", "S3 Cross-Region", "DynamoDB Global Tables", "Route53 ARC", "EKS"],
      gcp: ["Cloud DNS", "Cloud SQL (cross-region)", "GCS Dual-Region", "GKE Multi-Cluster"],
      azure: ["Traffic Manager", "Azure SQL Geo-Replication", "Blob Geo-Redundant", "AKS Fleet"],
      oci: ["DNS Traffic Steering", "Autonomous DB (Data Guard)", "Object Storage (Cross-Region)", "OKE Multi-Region"],
    },
    jitScope: ["route53:CreateHealthCheck", "rds:CreateGlobalCluster"],
    jitTtl: "5–20 min per layer",
    rmcmThreshold: 98,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["dr", "multi-region", "failover", "resilience"],
    status: "v1.0 — Planned (Phase 3)",
  },
  // ── V3 Intent Golden Paths (AWS) ─────────────────────────────────────────────

  {
    id: "storage",
    intentId: "naawi.v3.storage",
    name: "Storage",
    description: "S3 buckets, EFS filesystems, and EBS volumes. Deploy with versioning, object lock, or encryption; discover, destroy, and check status.",
    icon: "🗂️",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.99,
    estimatedDeployMin: 1,
    estimatedMonthlyCost: "$5–500",
    resources: { aws: ["S3 Bucket", "EFS Filesystem", "EBS Volume"], gcp: [], azure: [], oci: [] },
    jitScope: ["s3:CreateBucket", "elasticfilesystem:CreateFileSystem", "ec2:CreateVolume"],
    jitTtl: "1–2 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["storage", "s3", "efs", "ebs"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "database",
    intentId: "naawi.v3.database",
    name: "Database",
    description: "RDS (Postgres/MySQL), DynamoDB tables, and ElastiCache Redis. Full deploy/discover/destroy/status lifecycle.",
    icon: "🛢️",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 8,
    estimatedMonthlyCost: "$50–2000",
    resources: { aws: ["RDS Instance", "DynamoDB Table", "ElastiCache Replication Group"], gcp: [], azure: [], oci: [] },
    jitScope: ["rds:CreateDBInstance", "dynamodb:CreateTable", "elasticache:CreateReplicationGroup"],
    jitTtl: "3–10 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["database", "rds", "dynamodb", "elasticache"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "serverless",
    intentId: "naawi.v3.serverless",
    name: "Serverless",
    description: "Lambda functions and App Runner services. Deploy from S3 or ECR, list, delete, and check configuration.",
    icon: "⚙️",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 2,
    estimatedMonthlyCost: "$5–500",
    resources: { aws: ["Lambda Function", "App Runner Service"], gcp: [], azure: [], oci: [] },
    jitScope: ["lambda:CreateFunction", "apprunner:CreateService"],
    jitTtl: "1–3 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["serverless", "lambda", "apprunner", "functions"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "cdn",
    intentId: "naawi.v3.cdn",
    name: "CDN",
    description: "CloudFront distributions. Create with custom origin, list all distributions, delete, or check deployment status.",
    icon: "🌍",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.95,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$20–500",
    resources: { aws: ["CloudFront Distribution"], gcp: [], azure: [], oci: [] },
    jitScope: ["cloudfront:CreateDistribution", "cloudfront:DeleteDistribution"],
    jitTtl: "2–5 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["cdn", "cloudfront", "edge"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "dns",
    intentId: "naawi.v3.dns",
    name: "DNS",
    description: "Route 53 hosted zones. Create zones, list all, delete, or fetch zone details.",
    icon: "📡",
    providers: ["aws"],
    tier: "Foundation",
    sloAvailability: 99.99,
    estimatedDeployMin: 1,
    estimatedMonthlyCost: "$1–50",
    resources: { aws: ["Route 53 Hosted Zone"], gcp: [], azure: [], oci: [] },
    jitScope: ["route53:CreateHostedZone", "route53:DeleteHostedZone"],
    jitTtl: "1–2 min",
    rmcmThreshold: 92,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["dns", "route53", "networking"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "loadbalancer",
    intentId: "naawi.v3.loadbalancer",
    name: "Load Balancer",
    description: "Application and Network Load Balancers. Create with subnet config, list, delete by ARN, or check state.",
    icon: "⚖️",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.99,
    estimatedDeployMin: 3,
    estimatedMonthlyCost: "$20–200",
    resources: { aws: ["ALB / NLB"], gcp: [], azure: [], oci: [] },
    jitScope: ["elasticloadbalancing:CreateLoadBalancer", "elasticloadbalancing:DeleteLoadBalancer"],
    jitTtl: "2–4 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["loadbalancer", "alb", "nlb", "networking"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "security",
    intentId: "naawi.v3.security",
    name: "Security",
    description: "IAM roles, WAF Web ACLs, GuardDuty detectors, Security Hub, CloudTrail trails, and AWS Config recorders.",
    icon: "🛡️",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.99,
    estimatedDeployMin: 3,
    estimatedMonthlyCost: "$10–500",
    resources: { aws: ["IAM Role", "WAF Web ACL", "GuardDuty Detector", "Security Hub", "CloudTrail Trail", "Config Recorder"], gcp: [], azure: [], oci: [] },
    jitScope: ["iam:CreateRole", "wafv2:CreateWebACL", "guardduty:CreateDetector", "securityhub:EnableSecurityHub"],
    jitTtl: "1–5 min",
    rmcmThreshold: 98,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["security", "iam", "waf", "guardduty", "compliance"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "gateway",
    intentId: "naawi.v3.gateway",
    name: "Gateway",
    description: "API Gateway (HTTP APIs) and VPC Interface Endpoints. Create, list, delete, or describe.",
    icon: "🚪",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 2,
    estimatedMonthlyCost: "$10–300",
    resources: { aws: ["API Gateway (HTTP)", "VPC Interface Endpoint"], gcp: [], azure: [], oci: [] },
    jitScope: ["apigateway:POST", "ec2:CreateVpcEndpoint"],
    jitTtl: "1–3 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["gateway", "apigateway", "vpc-endpoint"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "secrets",
    intentId: "naawi.v3.secrets",
    name: "Secrets",
    description: "Secrets Manager secrets and KMS keys. Create, list, delete with recovery window, or describe.",
    icon: "🔐",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.99,
    estimatedDeployMin: 1,
    estimatedMonthlyCost: "$5–100",
    resources: { aws: ["Secrets Manager Secret", "KMS CMK"], gcp: [], azure: [], oci: [] },
    jitScope: ["secretsmanager:CreateSecret", "kms:CreateKey"],
    jitTtl: "1–2 min",
    rmcmThreshold: 98,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["secrets", "kms", "encryption", "security"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "observability",
    intentId: "naawi.v3.observability",
    name: "Observability",
    description: "CloudWatch alarms and log groups. Create alarms with thresholds, manage log groups with retention, list, delete, or check state.",
    icon: "📊",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 1,
    estimatedMonthlyCost: "$5–200",
    resources: { aws: ["CloudWatch Alarm", "CloudWatch Log Group"], gcp: [], azure: [], oci: [] },
    jitScope: ["cloudwatch:PutMetricAlarm", "logs:CreateLogGroup"],
    jitTtl: "1–2 min",
    rmcmThreshold: 88,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["observability", "cloudwatch", "alarms", "logs"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "orchestration",
    intentId: "naawi.v3.orchestration",
    name: "Orchestration",
    description: "Step Functions state machines, EventBridge event buses, and SSM Parameter Store. Full lifecycle management.",
    icon: "🎼",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 2,
    estimatedMonthlyCost: "$5–200",
    resources: { aws: ["Step Functions State Machine", "EventBridge Bus", "SSM Parameter"], gcp: [], azure: [], oci: [] },
    jitScope: ["states:CreateStateMachine", "events:CreateEventBus", "ssm:PutParameter"],
    jitTtl: "1–3 min",
    rmcmThreshold: 88,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["orchestration", "stepfunctions", "eventbridge", "ssm"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "ai",
    intentId: "naawi.v3.ai",
    name: "AI / ML",
    description: "Amazon Bedrock foundation model access and provisioned throughput. List models, provision capacity, or check status.",
    icon: "🤖",
    providers: ["aws"],
    tier: "AI-Ops",
    sloAvailability: 99.9,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$100–10000",
    resources: { aws: ["Bedrock Provisioned Throughput", "Foundation Models"], gcp: [], azure: [], oci: [] },
    jitScope: ["bedrock:CreateProvisionedModelThroughput", "bedrock:ListFoundationModels"],
    jitTtl: "3–10 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["ai", "bedrock", "ml", "foundation-models"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "container",
    intentId: "naawi.v3.container",
    name: "Container",
    description: "ECS Fargate clusters with Container Insights. Create, list, delete by ARN, or describe cluster state.",
    icon: "📦",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 3,
    estimatedMonthlyCost: "$50–2000",
    resources: { aws: ["ECS Fargate Cluster"], gcp: [], azure: [], oci: [] },
    jitScope: ["ecs:CreateCluster", "ecs:DeleteCluster"],
    jitTtl: "2–5 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["container", "ecs", "fargate"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "gap-analysis",
    intentId: "naawi.v3.gap-analysis",
    name: "Gap Analysis",
    description: "Audit and clean up orphaned resources: unused Elastic IPs, unattached EBS volumes, open security groups, dangling Route 53 records, and stale snapshots.",
    icon: "🔍",
    providers: ["aws"],
    tier: "Foundation",
    sloAvailability: 99.9,
    estimatedDeployMin: 1,
    estimatedMonthlyCost: "$0",
    resources: { aws: ["VPC", "Elastic IP", "EBS Snapshot", "Security Group", "EBS Volume", "Route 53 Record"], gcp: [], azure: [], oci: [] },
    jitScope: ["ec2:DescribeAddresses", "ec2:DescribeSnapshots", "ec2:DescribeVolumes", "ec2:ReleaseAddress"],
    jitTtl: "1–2 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["gap-analysis", "audit", "cleanup", "cost-optimization"],
    status: "v1.0 — Specification complete",
  },

  // ── Compute (Extended) ─────────────────────────────────────────────
  {
    id: "lightsail",
    intentId: "naawi.v4.lightsail",
    name: "Lightsail",
    description: "Simple virtual private servers, managed databases, and container services. Fixed pricing for small workloads.",
    icon: "💡",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 2,
    estimatedMonthlyCost: "$5–80",
    resources: { aws: ["Lightsail Instance", "Lightsail Database", "Lightsail Container Service", "Static IP"], gcp: [], azure: [], oci: [] },
    jitScope: ["lightsail:CreateInstances", "lightsail:CreateRelationalDatabase"],
    jitTtl: "1–3 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["compute", "lightsail", "simple", "vps"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "batch",
    intentId: "naawi.v4.batch",
    name: "AWS Batch",
    description: "Fully managed batch processing. Compute environments, job queues, and job definitions with Fargate or EC2.",
    icon: "📦",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$10–5000",
    resources: { aws: ["Batch Compute Environment", "Job Queue", "Job Definition"], gcp: [], azure: [], oci: [] },
    jitScope: ["batch:CreateComputeEnvironment", "batch:CreateJobQueue", "batch:RegisterJobDefinition"],
    jitTtl: "2–5 min",
    rmcmThreshold: 88,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["compute", "batch", "hpc", "jobs"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "elastic-beanstalk",
    intentId: "naawi.v4.elasticbeanstalk",
    name: "Elastic Beanstalk",
    description: "PaaS-style deployment. Upload code — Beanstalk handles capacity, load balancing, auto-scaling, and monitoring.",
    icon: "🌱",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 8,
    estimatedMonthlyCost: "$20–500",
    resources: { aws: ["Beanstalk Application", "Beanstalk Environment", "ALB", "ASG", "EC2 Instances"], gcp: [], azure: [], oci: [] },
    jitScope: ["elasticbeanstalk:CreateApplication", "elasticbeanstalk:CreateEnvironment"],
    jitTtl: "3–8 min",
    rmcmThreshold: 88,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["compute", "paas", "beanstalk", "deployment"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "ec2-image-builder",
    intentId: "naawi.v4.imagebuilder",
    name: "EC2 Image Builder",
    description: "Automate creation, testing, and distribution of VM and container images. Golden AMI pipelines with compliance validation.",
    icon: "🖼️",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.9,
    estimatedDeployMin: 15,
    estimatedMonthlyCost: "$5–100",
    resources: { aws: ["Image Pipeline", "Image Recipe", "Infrastructure Configuration", "Distribution Configuration"], gcp: [], azure: [], oci: [] },
    jitScope: ["imagebuilder:CreateImagePipeline", "imagebuilder:CreateImageRecipe"],
    jitTtl: "5–15 min",
    rmcmThreshold: 92,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["compute", "ami", "image-builder", "golden-ami"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "outposts",
    intentId: "naawi.v4.outposts",
    name: "AWS Outposts",
    description: "Run AWS infrastructure on-premises. Hybrid cloud with consistent APIs for data residency and low-latency needs.",
    icon: "🏭",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.9,
    estimatedDeployMin: 30,
    estimatedMonthlyCost: "$5000–50000",
    resources: { aws: ["Outpost", "Outpost Subnet", "Local EC2 Instances", "Local S3"], gcp: [], azure: [], oci: [] },
    jitScope: ["outposts:CreateOutpost", "ec2:CreateSubnet"],
    jitTtl: "10–30 min",
    rmcmThreshold: 95,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["compute", "hybrid", "outposts", "on-premises"],
    status: "v1.0 — Planned (Phase 3)",
  },
  {
    id: "parallel-computing",
    intentId: "naawi.v4.pcs",
    name: "Parallel Computing Service",
    description: "HPC clusters with Slurm scheduler. Scientific computing, CFD, genomics, and financial modeling.",
    icon: "⚛️",
    providers: ["aws"],
    tier: "AI-Ops",
    sloAvailability: 99.0,
    estimatedDeployMin: 20,
    estimatedMonthlyCost: "$500–50000",
    resources: { aws: ["PCS Cluster", "Compute Fleet", "Shared Storage (FSx)", "Placement Group"], gcp: [], azure: [], oci: [] },
    jitScope: ["pcs:CreateCluster", "fsx:CreateFileSystem"],
    jitTtl: "10–20 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["compute", "hpc", "parallel", "scientific"],
    status: "v1.0 — Planned (Phase 3)",
  },

  // ── Containers (Extended) ──────────────────────────────────────────
  {
    id: "ecr",
    intentId: "naawi.v4.ecr",
    name: "Elastic Container Registry",
    description: "Private Docker registries with image scanning, lifecycle policies, and cross-account replication.",
    icon: "🐋",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 1,
    estimatedMonthlyCost: "$1–100",
    resources: { aws: ["ECR Repository", "Lifecycle Policy", "Replication Configuration", "Pull-Through Cache Rule"], gcp: [], azure: [], oci: [] },
    jitScope: ["ecr:CreateRepository", "ecr:PutLifecyclePolicy"],
    jitTtl: "1–2 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["container", "ecr", "registry", "docker"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "rosa",
    intentId: "naawi.v4.rosa",
    name: "Red Hat OpenShift (ROSA)",
    description: "Managed Red Hat OpenShift clusters on AWS. Enterprise Kubernetes with OpenShift operator ecosystem.",
    icon: "🎩",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.9,
    estimatedDeployMin: 45,
    estimatedMonthlyCost: "$500–5000",
    resources: { aws: ["ROSA Cluster", "Machine Pools", "Identity Provider", "Network (PrivateLink)"], gcp: [], azure: [], oci: [] },
    jitScope: ["rosa:CreateCluster", "iam:CreateRole"],
    jitTtl: "15–45 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["container", "openshift", "rosa", "enterprise-k8s"],
    status: "v1.0 — Planned (Phase 3)",
  },

  // ── Storage (Extended) ─────────────────────────────────────────────
  {
    id: "s3-glacier",
    intentId: "naawi.v4.glacier",
    name: "S3 Glacier",
    description: "Long-term archive storage. Glacier Flexible Retrieval, Deep Archive, and Instant Retrieval tiers with vault lock.",
    icon: "🧊",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.99,
    estimatedDeployMin: 2,
    estimatedMonthlyCost: "$1–500",
    resources: { aws: ["S3 Bucket (Glacier Class)", "Glacier Vault", "Vault Lock Policy", "Lifecycle Rule"], gcp: [], azure: [], oci: [] },
    jitScope: ["glacier:CreateVault", "s3:PutLifecycleConfiguration"],
    jitTtl: "1–3 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["storage", "glacier", "archive", "cold-storage"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "storage-gateway",
    intentId: "naawi.v4.storagegateway",
    name: "Storage Gateway",
    description: "Hybrid cloud storage. File, Volume, and Tape gateways bridging on-premises to AWS cloud storage.",
    icon: "🔗",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 15,
    estimatedMonthlyCost: "$100–2000",
    resources: { aws: ["Storage Gateway", "File Share (NFS/SMB)", "Volume Gateway", "Tape Gateway"], gcp: [], azure: [], oci: [] },
    jitScope: ["storagegateway:CreateGateway", "storagegateway:CreateNFSFileShare"],
    jitTtl: "5–15 min",
    rmcmThreshold: 88,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["storage", "hybrid", "gateway", "nfs"],
    status: "v1.0 — Planned (Phase 3)",
  },
  {
    id: "aws-backup",
    intentId: "naawi.v4.backup",
    name: "AWS Backup",
    description: "Centralized backup across AWS services. Backup plans, vaults, cross-account/cross-region with compliance policies.",
    icon: "💾",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.99,
    estimatedDeployMin: 3,
    estimatedMonthlyCost: "$10–1000",
    resources: { aws: ["Backup Vault", "Backup Plan", "Backup Selection", "Vault Lock"], gcp: [], azure: [], oci: [] },
    jitScope: ["backup:CreateBackupVault", "backup:CreateBackupPlan"],
    jitTtl: "2–5 min",
    rmcmThreshold: 95,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["storage", "backup", "compliance", "disaster-recovery"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "elastic-disaster-recovery",
    intentId: "naawi.v4.drs",
    name: "Elastic Disaster Recovery",
    description: "Continuous replication into AWS. Sub-second RPO with automated failover and failback.",
    icon: "🔄",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.99,
    estimatedDeployMin: 20,
    estimatedMonthlyCost: "$100–3000",
    resources: { aws: ["DRS Source Server", "Replication Configuration", "Launch Configuration", "Recovery Instance"], gcp: [], azure: [], oci: [] },
    jitScope: ["drs:CreateSourceServer", "drs:StartReplication"],
    jitTtl: "10–20 min",
    rmcmThreshold: 95,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["storage", "disaster-recovery", "replication", "failover"],
    status: "v1.0 — Planned (Phase 3)",
  },
  {
    id: "fsx",
    intentId: "naawi.v4.fsx",
    name: "Amazon FSx",
    description: "Managed file systems: FSx for Lustre (HPC), Windows File Server, NetApp ONTAP, and OpenZFS.",
    icon: "📁",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$50–5000",
    resources: { aws: ["FSx File System", "FSx Backup", "Data Repository Association"], gcp: [], azure: [], oci: [] },
    jitScope: ["fsx:CreateFileSystem", "fsx:CreateBackup"],
    jitTtl: "5–10 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["storage", "fsx", "lustre", "file-system"],
    status: "v1.0 — Planned (Phase 2)",
  },

  // ── Database (Extended) ────────────────────────────────────────────
  {
    id: "neptune",
    intentId: "naawi.v4.neptune",
    name: "Amazon Neptune",
    description: "Managed graph database. Property graph and RDF models with Gremlin and SPARQL.",
    icon: "🔱",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 15,
    estimatedMonthlyCost: "$100–3000",
    resources: { aws: ["Neptune Cluster", "Neptune Instance", "Parameter Group", "Subnet Group"], gcp: [], azure: [], oci: [] },
    jitScope: ["neptune:CreateDBCluster", "neptune:CreateDBInstance"],
    jitTtl: "5–15 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["database", "neptune", "graph", "gremlin"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "documentdb",
    intentId: "naawi.v4.documentdb",
    name: "Amazon DocumentDB",
    description: "MongoDB-compatible document database. Auto-scaling storage, multi-AZ, and point-in-time recovery.",
    icon: "📋",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 12,
    estimatedMonthlyCost: "$100–3000",
    resources: { aws: ["DocumentDB Cluster", "DocumentDB Instance", "Parameter Group", "Subnet Group"], gcp: [], azure: [], oci: [] },
    jitScope: ["rds:CreateDBCluster", "rds:CreateDBInstance"],
    jitTtl: "5–12 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["database", "documentdb", "mongodb", "document"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "keyspaces",
    intentId: "naawi.v4.keyspaces",
    name: "Amazon Keyspaces",
    description: "Managed Apache Cassandra-compatible database. Serverless, pay-per-request with auto scaling.",
    icon: "🔑",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.99,
    estimatedDeployMin: 3,
    estimatedMonthlyCost: "$10–2000",
    resources: { aws: ["Keyspace", "Table", "Point-in-Time Recovery"], gcp: [], azure: [], oci: [] },
    jitScope: ["cassandra:Create", "cassandra:Alter"],
    jitTtl: "1–3 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["database", "keyspaces", "cassandra", "nosql"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "timestream",
    intentId: "naawi.v4.timestream",
    name: "Amazon Timestream",
    description: "Purpose-built time-series database for IoT sensor data, DevOps metrics, and analytics.",
    icon: "⏱️",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 3,
    estimatedMonthlyCost: "$10–2000",
    resources: { aws: ["Timestream Database", "Timestream Table", "Retention Policy"], gcp: [], azure: [], oci: [] },
    jitScope: ["timestream:CreateDatabase", "timestream:CreateTable"],
    jitTtl: "1–3 min",
    rmcmThreshold: 88,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["database", "timestream", "time-series", "iot"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "aurora-dsql",
    intentId: "naawi.v4.aurora-dsql",
    name: "Aurora DSQL",
    description: "Distributed SQL with PostgreSQL compatibility. Multi-region active-active with strong consistency.",
    icon: "🌏",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.999,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$200–10000",
    resources: { aws: ["Aurora DSQL Cluster", "Multi-Region Link", "Parameter Group"], gcp: [], azure: [], oci: [] },
    jitScope: ["dsql:CreateCluster"],
    jitTtl: "5–10 min",
    rmcmThreshold: 98,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["database", "aurora", "dsql", "distributed", "multi-region"],
    status: "v1.0 — Planned (Phase 3)",
  },
  {
    id: "memorydb",
    intentId: "naawi.v4.memorydb",
    name: "Amazon MemoryDB",
    description: "Redis-compatible, durable in-memory database. Multi-AZ with microsecond read latency.",
    icon: "⚡",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.99,
    estimatedDeployMin: 8,
    estimatedMonthlyCost: "$50–3000",
    resources: { aws: ["MemoryDB Cluster", "ACL", "Subnet Group", "Parameter Group"], gcp: [], azure: [], oci: [] },
    jitScope: ["memorydb:CreateCluster", "memorydb:CreateACL"],
    jitTtl: "3–8 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["database", "memorydb", "redis", "in-memory"],
    status: "v1.0 — Planned (Phase 2)",
  },

  // ── Migration & Transfer ───────────────────────────────────────────
  {
    id: "migration-transfer",
    intentId: "naawi.v4.migration",
    name: "Migration & Transfer",
    description: "Migration Hub, Application Migration Service, DMS, Transfer Family (SFTP/FTPS), DataSync, Snow Family, and Mainframe Modernization.",
    icon: "🚚",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 15,
    estimatedMonthlyCost: "$50–5000",
    resources: { aws: ["Migration Hub", "Application Migration Service", "DMS Replication Instance", "DMS Endpoint", "DMS Task", "Transfer Family Server", "DataSync Agent", "DataSync Task", "Snow Family Job", "M2 Application", "M2 Environment"], gcp: [], azure: [], oci: [] },
    jitScope: ["dms:CreateReplicationInstance", "dms:CreateEndpoint", "transfer:CreateServer", "datasync:CreateTask", "m2:CreateApplication"],
    jitTtl: "5–60 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["migration", "dms", "transfer", "datasync", "snow", "mainframe"],
    status: "v1.0 — Planned (Phase 2)",
  },

  // ── Networking (Extended) ──────────────────────────────────────────
  {
    id: "direct-connect",
    intentId: "naawi.v4.directconnect",
    name: "Direct Connect",
    description: "Dedicated network connections from on-premises to AWS. Virtual interfaces, LAG, and DX gateways.",
    icon: "🔌",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.99,
    estimatedDeployMin: 30,
    estimatedMonthlyCost: "$200–10000",
    resources: { aws: ["Direct Connect Connection", "Virtual Interface", "Direct Connect Gateway", "LAG"], gcp: [], azure: [], oci: [] },
    jitScope: ["directconnect:CreateConnection", "directconnect:CreatePrivateVirtualInterface"],
    jitTtl: "10–30 min",
    rmcmThreshold: 95,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["networking", "direct-connect", "hybrid", "dedicated"],
    status: "v1.0 — Planned (Phase 3)",
  },
  {
    id: "global-accelerator",
    intentId: "naawi.v4.globalaccelerator",
    name: "Global Accelerator",
    description: "Anycast static IPs on AWS global network with automatic failover for improved availability.",
    icon: "🚀",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.99,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$50–500",
    resources: { aws: ["Accelerator", "Listener", "Endpoint Group", "Static IP"], gcp: [], azure: [], oci: [] },
    jitScope: ["globalaccelerator:CreateAccelerator", "globalaccelerator:CreateListener"],
    jitTtl: "2–5 min",
    rmcmThreshold: 92,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["networking", "global-accelerator", "anycast", "performance"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "app-mesh",
    intentId: "naawi.v4.appmesh",
    name: "AWS App Mesh",
    description: "Application-level networking for microservices. Virtual services, nodes, routers, and gateways with Envoy.",
    icon: "🕸️",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.9,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$0–100",
    resources: { aws: ["Mesh", "Virtual Service", "Virtual Node", "Virtual Router", "Virtual Gateway"], gcp: [], azure: [], oci: [] },
    jitScope: ["appmesh:CreateMesh", "appmesh:CreateVirtualService"],
    jitTtl: "3–10 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["networking", "service-mesh", "envoy", "microservices"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "cloud-map",
    intentId: "naawi.v4.cloudmap",
    name: "AWS Cloud Map",
    description: "Service discovery for cloud resources. DNS-based and API-based discovery with health checking.",
    icon: "🗺️",
    providers: ["aws"],
    tier: "Foundation",
    sloAvailability: 99.99,
    estimatedDeployMin: 2,
    estimatedMonthlyCost: "$1–20",
    resources: { aws: ["Cloud Map Namespace", "Service", "Service Instance"], gcp: [], azure: [], oci: [] },
    jitScope: ["servicediscovery:CreatePrivateDnsNamespace", "servicediscovery:CreateService"],
    jitTtl: "1–2 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["networking", "service-discovery", "cloud-map", "dns"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "vpc-privatelink",
    intentId: "naawi.v4.privatelink",
    name: "PrivateLink & VPC Endpoints",
    description: "Private connectivity to AWS services and SaaS. Interface and Gateway endpoints without internet traversal.",
    icon: "🔒",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.99,
    estimatedDeployMin: 3,
    estimatedMonthlyCost: "$10–500",
    resources: { aws: ["VPC Endpoint (Interface)", "VPC Endpoint (Gateway)", "Endpoint Service", "Endpoint Connection"], gcp: [], azure: [], oci: [] },
    jitScope: ["ec2:CreateVpcEndpoint", "ec2:CreateVpcEndpointServiceConfiguration"],
    jitTtl: "1–3 min",
    rmcmThreshold: 95,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["networking", "privatelink", "vpc-endpoint", "zero-trust"],
    status: "v1.0 — Specification complete",
  },

  // ── Developer Tools ────────────────────────────────────────────────
  {
    id: "devtools-cicd",
    intentId: "naawi.v4.devtools",
    name: "Developer Tools (CI/CD)",
    description: "CodeBuild, CodeDeploy, CodePipeline, CodeArtifact, and CodeCommit. Complete CI/CD with blue/green deployments.",
    icon: "🛠️",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$10–500",
    resources: { aws: ["CodeBuild Project", "CodeDeploy Application", "CodePipeline", "CodeArtifact Repository", "CodeCommit Repository", "CodeCatalyst Space"], gcp: [], azure: [], oci: [] },
    jitScope: ["codebuild:CreateProject", "codedeploy:CreateApplication", "codepipeline:CreatePipeline"],
    jitTtl: "3–10 min",
    rmcmThreshold: 88,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["devtools", "cicd", "codebuild", "codedeploy", "pipeline"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "xray-fis",
    intentId: "naawi.v4.xray-fis",
    name: "X-Ray & Fault Injection",
    description: "Distributed tracing with X-Ray and chaos engineering with AWS FIS. Trace requests and test resilience.",
    icon: "🔬",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$5–200",
    resources: { aws: ["X-Ray Group", "X-Ray Sampling Rule", "FIS Experiment Template", "FIS Experiment"], gcp: [], azure: [], oci: [] },
    jitScope: ["xray:CreateGroup", "fis:CreateExperimentTemplate"],
    jitTtl: "2–5 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["devtools", "xray", "fis", "chaos", "tracing"],
    status: "v1.0 — Planned (Phase 2)",
  },

  // ── Management & Governance ────────────────────────────────────────
  {
    id: "organizations",
    intentId: "naawi.v4.organizations",
    name: "AWS Organizations",
    description: "Multi-account management with SCPs, OUs, and consolidated billing. Enterprise landing zone governance.",
    icon: "🏢",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.99,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$0",
    resources: { aws: ["Organization", "Organizational Unit", "Service Control Policy", "Account"], gcp: [], azure: [], oci: [] },
    jitScope: ["organizations:CreateOrganization", "organizations:CreateOrganizationalUnit", "organizations:CreatePolicy"],
    jitTtl: "3–10 min",
    rmcmThreshold: 98,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["governance", "organizations", "scp", "multi-account"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "cloudformation",
    intentId: "naawi.v4.cloudformation",
    name: "CloudFormation",
    description: "IaC stacks, stack sets, and change sets. Cross-account/region deployments with drift detection.",
    icon: "📜",
    providers: ["aws"],
    tier: "Foundation",
    sloAvailability: 99.99,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$0",
    resources: { aws: ["Stack", "Stack Set", "Change Set", "StackSet Instance"], gcp: [], azure: [], oci: [] },
    jitScope: ["cloudformation:CreateStack", "cloudformation:CreateStackSet"],
    jitTtl: "2–5 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["governance", "cloudformation", "iac", "stacks"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "control-tower",
    intentId: "naawi.v4.controltower",
    name: "Control Tower",
    description: "Automated landing zone with guardrails. Account Factory with detective/preventive controls.",
    icon: "🗼",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.99,
    estimatedDeployMin: 60,
    estimatedMonthlyCost: "$0–100",
    resources: { aws: ["Landing Zone", "Control (Guardrail)", "Account Factory", "Enrolled Account"], gcp: [], azure: [], oci: [] },
    jitScope: ["controltower:CreateLandingZone", "controltower:EnableControl"],
    jitTtl: "30–60 min",
    rmcmThreshold: 98,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["governance", "control-tower", "landing-zone", "guardrails"],
    status: "v1.0 — Planned (Phase 3)",
  },
  {
    id: "auto-scaling",
    intentId: "naawi.v4.autoscaling",
    name: "Auto Scaling",
    description: "EC2 Auto Scaling Groups, Launch Templates, scaling policies, and predictive scaling.",
    icon: "📈",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$0",
    resources: { aws: ["Auto Scaling Group", "Launch Template", "Scaling Policy", "Scheduled Action"], gcp: [], azure: [], oci: [] },
    jitScope: ["autoscaling:CreateAutoScalingGroup", "ec2:CreateLaunchTemplate"],
    jitTtl: "2–5 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["compute", "autoscaling", "asg", "scaling"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "service-catalog",
    intentId: "naawi.v4.servicecatalog",
    name: "Service Catalog",
    description: "Curated catalog of approved AWS products. Portfolios, products, and launch constraints for self-service IT.",
    icon: "📚",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.9,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$0",
    resources: { aws: ["Portfolio", "Product", "Launch Constraint", "Provisioned Product"], gcp: [], azure: [], oci: [] },
    jitScope: ["servicecatalog:CreatePortfolio", "servicecatalog:CreateProduct"],
    jitTtl: "3–10 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["governance", "service-catalog", "self-service", "compliance"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "config-rules",
    intentId: "naawi.v4.config-rules",
    name: "AWS Config Rules",
    description: "Evaluate resource configurations against desired settings. Managed/custom rules with automated remediation.",
    icon: "⚙️",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.9,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$5–100",
    resources: { aws: ["Config Rule", "Remediation Configuration", "Conformance Pack", "Configuration Recorder"], gcp: [], azure: [], oci: [] },
    jitScope: ["config:PutConfigRule", "config:PutRemediationConfigurations"],
    jitTtl: "2–5 min",
    rmcmThreshold: 95,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["governance", "config", "compliance", "remediation"],
    status: "v1.0 — Specification complete",
  },
  {
    id: "grafana-prometheus",
    intentId: "naawi.v4.managed-monitoring",
    name: "Managed Grafana & Prometheus",
    description: "Amazon Managed Grafana and Prometheus workspaces for cloud-native monitoring without ops overhead.",
    icon: "📊",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$50–1000",
    resources: { aws: ["Grafana Workspace", "Prometheus Workspace", "Alert Manager", "Rule Groups"], gcp: [], azure: [], oci: [] },
    jitScope: ["grafana:CreateWorkspace", "aps:CreateWorkspace"],
    jitTtl: "2–5 min",
    rmcmThreshold: 88,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["observability", "grafana", "prometheus", "monitoring"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "resilience-hub",
    intentId: "naawi.v4.resiliencehub",
    name: "Resilience Hub",
    description: "Define and validate application resilience. RTO/RPO targets with resilience assessments and recommendations.",
    icon: "🏰",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.9,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$0–50",
    resources: { aws: ["Resilience Policy", "Application", "Assessment", "Recommendation"], gcp: [], azure: [], oci: [] },
    jitScope: ["resiliencehub:CreateApp", "resiliencehub:CreateResiliencyPolicy"],
    jitTtl: "3–10 min",
    rmcmThreshold: 95,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["governance", "resilience", "rto", "rpo", "disaster-recovery"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "trusted-advisor",
    intentId: "naawi.v4.trustedadvisor",
    name: "Trusted Advisor",
    description: "Best practice checks for cost, performance, security, fault tolerance, and service limits.",
    icon: "🧭",
    providers: ["aws"],
    tier: "Foundation",
    sloAvailability: 99.9,
    estimatedDeployMin: 1,
    estimatedMonthlyCost: "$0",
    resources: { aws: ["Trusted Advisor Check", "Organizational View", "Notification Preferences"], gcp: [], azure: [], oci: [] },
    jitScope: ["trustedadvisor:DescribeChecks", "trustedadvisor:RefreshCheck"],
    jitTtl: "1–2 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["governance", "trusted-advisor", "best-practices", "cost"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "compute-optimizer",
    intentId: "naawi.v4.computeoptimizer",
    name: "Compute Optimizer",
    description: "ML-powered right-sizing recommendations for EC2, EBS, Lambda, ECS, and Auto Scaling.",
    icon: "🎯",
    providers: ["aws"],
    tier: "AI-Ops",
    sloAvailability: 99.9,
    estimatedDeployMin: 1,
    estimatedMonthlyCost: "$0",
    resources: { aws: ["Compute Optimizer Enrollment", "EC2 Recommendations", "EBS Recommendations", "Lambda Recommendations"], gcp: [], azure: [], oci: [] },
    jitScope: ["compute-optimizer:GetEC2InstanceRecommendations"],
    jitTtl: "1 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["governance", "optimizer", "right-sizing", "cost"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "incident-manager",
    intentId: "naawi.v4.incidentmanager",
    name: "Incident Manager",
    description: "Automated incident response plans, escalation paths, and post-incident analysis.",
    icon: "🚨",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.9,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$0–50",
    resources: { aws: ["Response Plan", "Escalation Plan", "Contact", "Replication Set"], gcp: [], azure: [], oci: [] },
    jitScope: ["ssm-incidents:CreateResponsePlan", "ssm-contacts:CreateContact"],
    jitTtl: "2–5 min",
    rmcmThreshold: 92,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["governance", "incident-manager", "ops", "response"],
    status: "v1.0 — Planned (Phase 2)",
  },

  // ── Media Services ─────────────────────────────────────────────────
  {
    id: "media-services",
    intentId: "naawi.v4.media",
    name: "Media Services",
    description: "MediaConvert, MediaLive, MediaPackage, IVS, Kinesis Video Streams, MediaConnect, and Deadline Cloud.",
    icon: "🎬",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$50–10000",
    resources: { aws: ["MediaConvert Job Template", "MediaLive Channel", "MediaPackage Channel", "IVS Channel", "Kinesis Video Stream", "MediaConnect Flow", "Deadline Cloud Farm"], gcp: [], azure: [], oci: [] },
    jitScope: ["mediaconvert:CreateJobTemplate", "medialive:CreateChannel", "ivs:CreateChannel"],
    jitTtl: "3–10 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["media", "video", "streaming", "transcoding", "ivs"],
    status: "v1.0 — Planned (Phase 3)",
  },

  // ── Machine Learning (Extended) ────────────────────────────────────
  {
    id: "sagemaker",
    intentId: "naawi.v4.sagemaker",
    name: "Amazon SageMaker AI",
    description: "End-to-end ML platform. Notebooks, training jobs, endpoints, model registry, pipelines, and feature store.",
    icon: "🧪",
    providers: ["aws"],
    tier: "AI-Ops",
    sloAvailability: 99.9,
    estimatedDeployMin: 15,
    estimatedMonthlyCost: "$100–20000",
    resources: { aws: ["SageMaker Domain", "Notebook Instance", "Training Job", "Endpoint", "Model", "Pipeline", "Feature Group"], gcp: [], azure: [], oci: [] },
    jitScope: ["sagemaker:CreateDomain", "sagemaker:CreateEndpoint", "sagemaker:CreateTrainingJob"],
    jitTtl: "5–15 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["ml", "sagemaker", "training", "inference", "mlops"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "ml-ai-services",
    intentId: "naawi.v4.ml-ai-services",
    name: "AI/ML Services",
    description: "Comprehend (NLP), Rekognition (vision), Textract (OCR), Transcribe, Translate, Polly, Lex, Personalize, Forecast, and Fraud Detector.",
    icon: "🤖",
    providers: ["aws"],
    tier: "AI-Ops",
    sloAvailability: 99.9,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$10–5000",
    resources: { aws: ["Comprehend Endpoint", "Rekognition Collection", "Textract Adapter", "Transcribe Vocabulary", "Translate Terminology", "Polly Lexicon", "Lex Bot", "Personalize Campaign", "Forecast Predictor", "Fraud Detector"], gcp: [], azure: [], oci: [] },
    jitScope: ["comprehend:CreateEndpoint", "rekognition:CreateCollection", "lex:CreateBot"],
    jitTtl: "2–10 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["ml", "ai", "nlp", "vision", "comprehend", "rekognition"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "bedrock-agents",
    intentId: "naawi.v4.bedrock-agents",
    name: "Bedrock AgentCore",
    description: "Build and deploy AI agents with Bedrock. Agent definitions, knowledge bases, guardrails, and action groups.",
    icon: "🧬",
    providers: ["aws"],
    tier: "AI-Ops",
    sloAvailability: 99.9,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$50–10000",
    resources: { aws: ["Bedrock Agent", "Knowledge Base", "Guardrail", "Action Group", "Model Customization Job"], gcp: [], azure: [], oci: [] },
    jitScope: ["bedrock:CreateAgent", "bedrock:CreateKnowledgeBase", "bedrock:CreateGuardrail"],
    jitTtl: "3–10 min",
    rmcmThreshold: 88,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["ai", "bedrock", "agents", "knowledge-base", "guardrails"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "healthlake-omics",
    intentId: "naawi.v4.health",
    name: "HealthLake & HealthOmics",
    description: "HIPAA-eligible data stores. HealthLake (FHIR), HealthOmics (genomics), and HealthImaging (medical imaging).",
    icon: "🏥",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.9,
    estimatedDeployMin: 15,
    estimatedMonthlyCost: "$100–5000",
    resources: { aws: ["HealthLake Data Store", "Omics Workflow", "Omics Sequence Store", "HealthImaging Data Store"], gcp: [], azure: [], oci: [] },
    jitScope: ["healthlake:CreateFHIRDatastore", "omics:CreateWorkflow"],
    jitTtl: "5–15 min",
    rmcmThreshold: 95,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["ml", "healthcare", "hipaa", "genomics", "fhir"],
    status: "v1.0 — Planned (Phase 3)",
  },

  // ── Analytics ──────────────────────────────────────────────────────
  {
    id: "analytics-query",
    intentId: "naawi.v4.analytics-query",
    name: "Analytics (Query Engines)",
    description: "Athena (serverless SQL), Redshift (warehouse), OpenSearch (search & analytics), and CloudSearch.",
    icon: "🔎",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$50–10000",
    resources: { aws: ["Athena Workgroup", "Redshift Cluster", "Redshift Serverless Namespace", "OpenSearch Domain", "CloudSearch Domain"], gcp: [], azure: [], oci: [] },
    jitScope: ["athena:CreateWorkGroup", "redshift:CreateCluster", "es:CreateDomain"],
    jitTtl: "5–15 min",
    rmcmThreshold: 88,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["analytics", "athena", "redshift", "opensearch", "query"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "analytics-streaming",
    intentId: "naawi.v4.analytics-streaming",
    name: "Analytics (Streaming & ETL)",
    description: "Kinesis, Data Firehose, MSK (Kafka), Managed Flink, EMR, and Glue for real-time and batch data processing.",
    icon: "🌊",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$50–10000",
    resources: { aws: ["Kinesis Stream", "Data Firehose Delivery Stream", "MSK Cluster", "Managed Flink Application", "EMR Cluster", "Glue Job", "Glue Crawler", "Glue Database"], gcp: [], azure: [], oci: [] },
    jitScope: ["kinesis:CreateStream", "firehose:CreateDeliveryStream", "kafka:CreateCluster", "elasticmapreduce:RunJobFlow"],
    jitTtl: "5–15 min",
    rmcmThreshold: 88,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["analytics", "kinesis", "kafka", "msk", "emr", "glue", "streaming"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "analytics-governance",
    intentId: "naawi.v4.analytics-governance",
    name: "Analytics (Governance & BI)",
    description: "Lake Formation, DataZone, QuickSight, Data Exchange, Clean Rooms, and Entity Resolution.",
    icon: "📈",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$20–5000",
    resources: { aws: ["Lake Formation Data Lake", "DataZone Domain", "QuickSight Dashboard", "Data Exchange Data Set", "Clean Room Collaboration", "Entity Resolution Workflow"], gcp: [], azure: [], oci: [] },
    jitScope: ["lakeformation:RegisterResource", "datazone:CreateDomain", "quicksight:CreateDashboard"],
    jitTtl: "3–10 min",
    rmcmThreshold: 88,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["analytics", "lakeformation", "quicksight", "datazone", "bi"],
    status: "v1.0 — Planned (Phase 2)",
  },

  // ── Security (Extended) ────────────────────────────────────────────
  {
    id: "identity-access",
    intentId: "naawi.v4.identity",
    name: "Identity & Access",
    description: "Cognito, IAM Identity Center (SSO), RAM, Directory Service, and Amazon Verified Permissions (Cedar).",
    icon: "👤",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.99,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$0–500",
    resources: { aws: ["Cognito User Pool", "Cognito Identity Pool", "IAM Identity Center Instance", "RAM Resource Share", "Directory Service Directory", "Verified Permissions Policy Store"], gcp: [], azure: [], oci: [] },
    jitScope: ["cognito-idp:CreateUserPool", "sso:CreateInstance", "ram:CreateResourceShare"],
    jitTtl: "3–10 min",
    rmcmThreshold: 98,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["security", "cognito", "sso", "identity", "directory"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "security-detection",
    intentId: "naawi.v4.detection",
    name: "Security Detection",
    description: "Inspector (vulnerability scanning), Macie (data discovery), Detective (investigation), Security Lake, and Audit Manager.",
    icon: "🔍",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.9,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$10–1000",
    resources: { aws: ["Inspector Assessment", "Macie Classification Job", "Detective Graph", "Security Lake", "Audit Manager Assessment"], gcp: [], azure: [], oci: [] },
    jitScope: ["inspector2:Enable", "macie2:EnableMacie", "detective:CreateGraph"],
    jitTtl: "2–5 min",
    rmcmThreshold: 95,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["security", "inspector", "macie", "detective", "audit"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "certificate-crypto",
    intentId: "naawi.v4.certificates",
    name: "Certificates & Cryptography",
    description: "ACM (TLS certs), CloudHSM, Private CA, Payment Cryptography, and AWS Signer.",
    icon: "📜",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.99,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$10–2000",
    resources: { aws: ["ACM Certificate", "CloudHSM Cluster", "Private CA", "Payment Cryptography Key", "Signer Profile"], gcp: [], azure: [], oci: [] },
    jitScope: ["acm:RequestCertificate", "cloudhsmv2:CreateCluster", "acm-pca:CreateCertificateAuthority"],
    jitTtl: "2–10 min",
    rmcmThreshold: 98,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["security", "acm", "tls", "cloudhsm", "pca", "crypto"],
    status: "v1.0 — Planned (Phase 2)",
  },
  {
    id: "firewall-shield",
    intentId: "naawi.v4.firewall",
    name: "Firewall & DDoS Protection",
    description: "Firewall Manager, WAF & Shield Advanced, and Network Firewall for centralized security and DDoS mitigation.",
    icon: "🧱",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.99,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$100–5000",
    resources: { aws: ["Firewall Manager Policy", "Network Firewall", "Firewall Rule Group", "Shield Advanced Protection", "Shield Response Team"], gcp: [], azure: [], oci: [] },
    jitScope: ["fms:PutPolicy", "network-firewall:CreateFirewall", "shield:CreateProtection"],
    jitTtl: "3–10 min",
    rmcmThreshold: 98,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["security", "firewall", "shield", "ddos", "network-firewall"],
    status: "v1.0 — Planned (Phase 2)",
  },

  // ── Application Integration ────────────────────────────────────────
  {
    id: "messaging",
    intentId: "naawi.v4.messaging",
    name: "Messaging & Queues",
    description: "SNS topics, SQS queues, Amazon MQ, AppFlow, and Managed Apache Airflow (MWAA).",
    icon: "📬",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 3,
    estimatedMonthlyCost: "$5–1000",
    resources: { aws: ["SNS Topic", "SQS Queue", "SQS DLQ", "Amazon MQ Broker", "AppFlow Flow", "MWAA Environment"], gcp: [], azure: [], oci: [] },
    jitScope: ["sns:CreateTopic", "sqs:CreateQueue", "mq:CreateBroker", "airflow:CreateEnvironment"],
    jitTtl: "1–5 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["integration", "sns", "sqs", "mq", "airflow", "messaging"],
    status: "v1.0 — Specification complete",
  },

  // ── Front-End & Mobile ─────────────────────────────────────────────
  {
    id: "frontend-mobile",
    intentId: "naawi.v4.frontend",
    name: "Front-End & Mobile",
    description: "Amplify (hosting & backend), AppSync (GraphQL), Device Farm (testing), and Location Service (maps & geofencing).",
    icon: "📱",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$5–500",
    resources: { aws: ["Amplify App", "Amplify Branch", "AppSync API", "Device Farm Project", "Location Service Map", "Location Service Geofence"], gcp: [], azure: [], oci: [] },
    jitScope: ["amplify:CreateApp", "appsync:CreateGraphqlApi", "devicefarm:CreateProject"],
    jitTtl: "2–5 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["frontend", "amplify", "appsync", "graphql", "mobile"],
    status: "v1.0 — Planned (Phase 2)",
  },

  // ── Business Applications ──────────────────────────────────────────
  {
    id: "business-apps",
    intentId: "naawi.v4.business",
    name: "Business Applications",
    description: "Amazon Connect, SES, Pinpoint, WorkMail, WorkDocs, Chime SDK, Supply Chain, and Wickr.",
    icon: "💼",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$10–5000",
    resources: { aws: ["Connect Instance", "SES Configuration Set", "SES Email Identity", "Pinpoint Application", "WorkMail Organization", "WorkDocs Site", "Chime SDK Voice Connector", "Supply Chain Instance", "Wickr Network"], gcp: [], azure: [], oci: [] },
    jitScope: ["connect:CreateInstance", "ses:CreateConfigurationSet", "pinpoint:CreateApp"],
    jitTtl: "3–10 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["business", "connect", "ses", "pinpoint", "email"],
    status: "v1.0 — Planned (Phase 2)",
  },

  // ── End User Computing ─────────────────────────────────────────────
  {
    id: "end-user-computing",
    intentId: "naawi.v4.euc",
    name: "End User Computing",
    description: "WorkSpaces (virtual desktops), Thin Client, and Secure Browser for remote work.",
    icon: "🖥️",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 15,
    estimatedMonthlyCost: "$25–200/user",
    resources: { aws: ["WorkSpaces Directory", "WorkSpace", "WorkSpaces Pool", "Secure Browser Portal"], gcp: [], azure: [], oci: [] },
    jitScope: ["workspaces:CreateWorkspaces", "workspaces:RegisterWorkspaceDirectory"],
    jitTtl: "5–15 min",
    rmcmThreshold: 88,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["euc", "workspaces", "virtual-desktop", "remote-work"],
    status: "v1.0 — Planned (Phase 3)",
  },

  // ── IoT ────────────────────────────────────────────────────────────
  {
    id: "iot",
    intentId: "naawi.v4.iot",
    name: "Internet of Things",
    description: "IoT Core (MQTT), Greengrass (edge), SiteWise (industrial), TwinMaker (digital twins), Events, FleetWise, and Device Defender.",
    icon: "📡",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$10–5000",
    resources: { aws: ["IoT Thing", "IoT Policy", "IoT Rule", "Greengrass Core Device", "SiteWise Gateway", "TwinMaker Workspace", "IoT Events Detector", "FleetWise Campaign", "Device Defender Audit"], gcp: [], azure: [], oci: [] },
    jitScope: ["iot:CreateThing", "iot:CreatePolicy", "greengrass:CreateCoreDevice"],
    jitTtl: "3–10 min",
    rmcmThreshold: 88,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["iot", "mqtt", "greengrass", "sitewise", "edge"],
    status: "v1.0 — Planned (Phase 2)",
  },

  // ── Game Development ───────────────────────────────────────────────
  {
    id: "game-dev",
    intentId: "naawi.v4.game",
    name: "Game Development",
    description: "GameLift Servers (multiplayer hosting) and GameLift Streams (cloud game streaming). Fleet management and matchmaking.",
    icon: "🎮",
    providers: ["aws"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 15,
    estimatedMonthlyCost: "$100–10000",
    resources: { aws: ["GameLift Fleet", "GameLift Matchmaking Config", "GameLift Game Session Queue", "GameLift Streams Application"], gcp: [], azure: [], oci: [] },
    jitScope: ["gamelift:CreateFleet", "gamelift:CreateMatchmakingConfiguration"],
    jitTtl: "5–15 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["game", "gamelift", "multiplayer", "streaming"],
    status: "v1.0 — Planned (Phase 3)",
  },

  // ── Blockchain, Quantum, Satellite ─────────────────────────────────
  {
    id: "blockchain",
    intentId: "naawi.v4.blockchain",
    name: "Managed Blockchain",
    description: "Blockchain networks with Hyperledger Fabric and Ethereum. AMB Access and AMB Query.",
    icon: "⛓️",
    providers: ["aws"],
    tier: "Hardened",
    sloAvailability: 99.9,
    estimatedDeployMin: 30,
    estimatedMonthlyCost: "$200–5000",
    resources: { aws: ["Blockchain Network", "Blockchain Member", "Blockchain Node", "AMB Access Endpoint"], gcp: [], azure: [], oci: [] },
    jitScope: ["managedblockchain:CreateNetwork", "managedblockchain:CreateMember"],
    jitTtl: "10–30 min",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["blockchain", "hyperledger", "ethereum", "web3"],
    status: "v1.0 — Planned (Phase 3)",
  },
  {
    id: "quantum",
    intentId: "naawi.v4.quantum",
    name: "Amazon Braket",
    description: "Quantum computing. Access quantum hardware (IonQ, Rigetti, IQM), run circuits, and manage hybrid jobs.",
    icon: "🔮",
    providers: ["aws"],
    tier: "AI-Ops",
    sloAvailability: 99.0,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$0–50000",
    resources: { aws: ["Braket Quantum Task", "Braket Hybrid Job", "Braket Notebook Instance"], gcp: [], azure: [], oci: [] },
    jitScope: ["braket:CreateQuantumTask", "braket:CreateJob"],
    jitTtl: "2–5 min",
    rmcmThreshold: 80,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["quantum", "braket", "computing", "research"],
    status: "v1.0 — Planned (Phase 3)",
  },
  {
    id: "ground-station",
    intentId: "naawi.v4.groundstation",
    name: "AWS Ground Station",
    description: "Satellite communications. Schedule contacts, downlink data, and process satellite imagery at scale.",
    icon: "🛰️",
    providers: ["aws"],
    tier: "AI-Ops",
    sloAvailability: 99.0,
    estimatedDeployMin: 30,
    estimatedMonthlyCost: "$500–50000",
    resources: { aws: ["Ground Station Mission Profile", "Ground Station Config", "Ground Station Contact", "Dataflow Endpoint Group"], gcp: [], azure: [], oci: [] },
    jitScope: ["groundstation:CreateMissionProfile", "groundstation:CreateConfig"],
    jitTtl: "10–30 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["satellite", "ground-station", "space", "downlink"],
    status: "v1.0 — Planned (Phase 3)",
  },

  // ── Cloud Financial Management ─────────────────────────────────────
  {
    id: "cost-management",
    intentId: "naawi.v4.cost",
    name: "Cloud Financial Management",
    description: "Billing, Cost Explorer, Budgets, Billing Conductor, Marketplace subscriptions, and Savings Plans.",
    icon: "💰",
    providers: ["aws"],
    tier: "Foundation",
    sloAvailability: 99.9,
    estimatedDeployMin: 3,
    estimatedMonthlyCost: "$0",
    resources: { aws: ["Budget", "Cost Anomaly Monitor", "Billing Conductor Pricing Rule", "Marketplace Subscription", "Savings Plan"], gcp: [], azure: [], oci: [] },
    jitScope: ["budgets:CreateBudget", "ce:CreateAnomalyMonitor"],
    jitTtl: "1–3 min",
    rmcmThreshold: 85,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["finops", "billing", "budgets", "cost", "marketplace"],
    status: "v1.0 — Planned (Phase 2)",
  },

  // ── Customer Enablement ────────────────────────────────────────────
  {
    id: "customer-enablement",
    intentId: "naawi.v4.enablement",
    name: "Customer Enablement & Support",
    description: "AWS IQ, Managed Services, Activate for Startups, re:Post Private, and Support plans.",
    icon: "🤝",
    providers: ["aws"],
    tier: "Foundation",
    sloAvailability: 99.9,
    estimatedDeployMin: 5,
    estimatedMonthlyCost: "$0–15000",
    resources: { aws: ["Support Plan", "re:Post Private Space", "IQ Project", "Activate Credits"], gcp: [], azure: [], oci: [] },
    jitScope: ["support:DescribeTrustedAdvisorChecks"],
    jitTtl: "1–5 min",
    rmcmThreshold: 80,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["support", "enablement", "startups", "managed-services"],
    status: "v1.0 — Planned (Phase 3)",
  },

  {
    id: "openclaw-cloud",
    intentId: "naawi.gold.v1.OpenClawCloud",
    name: "OpenClaw Cloud Deployment (GP2)",
    description: "Production topology for always-on operation: Linux VPS gateway (systemd) + macOS node (OpenClaw.app) connected over Tailscale WebSocket. No public ports. Nix-managed, reproducible, agent-first.",
    icon: "🦞",
    providers: ["aws", "gcp", "azure", "oci"],
    tier: "Standard",
    sloAvailability: 99.9,
    estimatedDeployMin: 10,
    estimatedMonthlyCost: "$20–100",
    resources: {
      aws: ["EC2 (VPS Gateway)", "Tailscale Tailnet", "Nix Flake", "systemd Service", "OpenClaw.app Node"],
      gcp: ["Compute Engine (VPS Gateway)", "Tailscale Tailnet", "Nix Flake", "systemd Service", "OpenClaw.app Node"],
      azure: ["Linux VM (VPS Gateway)", "Tailscale Tailnet", "Nix Flake", "systemd Service", "OpenClaw.app Node"],
      oci: ["Compute (VPS Gateway)", "Tailscale Tailnet", "Nix Flake", "systemd Service", "OpenClaw.app Node"],
    },
    jitScope: ["ec2:RunInstances", "ec2:CreateSecurityGroup"],
    jitTtl: "3–8 min per layer",
    rmcmThreshold: 90,
    preflightSteps: PREFLIGHT_STANDARD,
    doltTables: ["resources", "resource_raw", "ztai_refs"],
    tags: ["openclaw", "agent-first", "tailscale", "nix", "macos", "gateway"],
    status: "v1.0 — Specification complete",
  },
];

const PROVIDER_LABELS: Record<CloudProvider, { label: string; color: string }> = {
  aws: { label: "AWS", color: "bg-amber-500/10 text-amber-400 border-amber-500/20" },
  gcp: { label: "GCP", color: "bg-blue-500/10 text-blue-400 border-blue-500/20" },
  azure: { label: "Azure", color: "bg-sky-500/10 text-sky-400 border-sky-500/20" },
  oci: { label: "OCI", color: "bg-red-500/10 text-red-400 border-red-500/20" },
};

const TIER_COLORS: Record<string, string> = {
  Foundation: "border-primary/30 text-primary",
  Standard: "border-emerald-500/30 text-emerald-400",
  Hardened: "border-amber-500/30 text-amber-400",
  "AI-Ops": "border-violet-500/30 text-violet-400",
};

const STATUS_COLORS: Record<string, string> = {
  "v1.0 — Specification complete": "text-emerald-400",
  "v1.0 — Planned (Phase 2)": "text-amber-400",
  "v1.0 — Planned (Phase 3)": "text-muted-foreground",
};

interface GoldenPathCatalogProps {
  onSelect: (entry: GoldenPathEntry, provider: CloudProvider) => void;
}

export function GoldenPathCatalog({ onSelect }: GoldenPathCatalogProps) {
  const [search, setSearch] = useState("");
  const [tierFilter, setTierFilter] = useState<string>("all");
  const [providerFilter, setProviderFilter] = useState<CloudProvider | "all">("all");

  const filtered = CATALOG.filter((entry) => {
    if (tierFilter !== "all" && entry.tier !== tierFilter) return false;
    if (providerFilter !== "all" && !entry.providers.includes(providerFilter)) return false;
    if (search) {
      const q = search.toLowerCase();
      return (
        entry.name.toLowerCase().includes(q) ||
        entry.description.toLowerCase().includes(q) ||
        entry.intentId.toLowerCase().includes(q) ||
        entry.tags.some((t) => t.includes(q))
      );
    }
    return true;
  });

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3 flex-wrap">
        <div className="relative flex-1 min-w-[200px]">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
          <Input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search golden paths by name, intent ID, or tag…"
            className="pl-9 h-9 text-sm glass-panel border-border/50"
          />
        </div>
        <Tabs value={tierFilter} onValueChange={setTierFilter}>
          <TabsList className="glass-panel border-0 p-0.5 h-8">
            <TabsTrigger value="all" className="text-[10px] h-7 px-3 rounded-md">All</TabsTrigger>
            <TabsTrigger value="Foundation" className="text-[10px] h-7 px-3 rounded-md">Foundation</TabsTrigger>
            <TabsTrigger value="Standard" className="text-[10px] h-7 px-3 rounded-md">Standard</TabsTrigger>
            <TabsTrigger value="Hardened" className="text-[10px] h-7 px-3 rounded-md">Hardened</TabsTrigger>
            <TabsTrigger value="AI-Ops" className="text-[10px] h-7 px-3 rounded-md">AI-Ops</TabsTrigger>
          </TabsList>
        </Tabs>
        <Tabs value={providerFilter} onValueChange={(v) => setProviderFilter(v as CloudProvider | "all")}>
          <TabsList className="glass-panel border-0 p-0.5 h-8">
            <TabsTrigger value="all" className="text-[10px] h-7 px-3 rounded-md">All</TabsTrigger>
            <TabsTrigger value="aws" className="text-[10px] h-7 px-3 rounded-md">AWS</TabsTrigger>
            <TabsTrigger value="gcp" className="text-[10px] h-7 px-3 rounded-md">GCP</TabsTrigger>
            <TabsTrigger value="azure" className="text-[10px] h-7 px-3 rounded-md">Azure</TabsTrigger>
            <TabsTrigger value="oci" className="text-[10px] h-7 px-3 rounded-md">OCI</TabsTrigger>
          </TabsList>
        </Tabs>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {filtered.map((entry) => (
          <Card
            key={entry.id}
            className="glass-panel border-border/40 hover:border-primary/40 transition-all group"
          >
            <CardContent className="p-4 space-y-3">
              <div className="flex items-start justify-between">
                <div className="flex items-start gap-3">
                  <span className="text-2xl">{entry.icon}</span>
                  <div>
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-semibold text-sm text-foreground">{entry.name}</span>
                      <Badge variant="outline" className={`text-[8px] uppercase tracking-widest ${TIER_COLORS[entry.tier]}`}>
                        {entry.tier}
                      </Badge>
                    </div>
                    <code className="text-[10px] font-mono text-primary/70 block mt-0.5">{entry.intentId}</code>
                    <p className="text-xs text-muted-foreground mt-1 leading-relaxed">{entry.description}</p>
                  </div>
                </div>
              </div>

              {/* RMCM + JIT + Dolt indicators */}
              <div className="flex items-center gap-2 flex-wrap text-[9px]">
                <Badge variant="outline" className="gap-1 font-mono border-primary/20 text-primary">
                  <Eye className="h-2.5 w-2.5" /> RMCM ≥{entry.rmcmThreshold}%
                </Badge>
                <Badge variant="outline" className="gap-1 font-mono border-amber-500/20 text-amber-400">
                  <Lock className="h-2.5 w-2.5" /> JIT {entry.jitTtl}
                </Badge>
                <Badge variant="outline" className="gap-1 font-mono border-emerald-500/20 text-emerald-400">
                  <FileCheck className="h-2.5 w-2.5" /> {entry.doltTables.length} Dolt tables
                </Badge>
              </div>

              {/* Provider pills */}
              <div className="flex items-center gap-1.5 flex-wrap">
                {entry.providers.map((p) => (
                  <Badge
                    key={p}
                    variant="outline"
                    className={`text-[9px] font-mono ${PROVIDER_LABELS[p].color}`}
                  >
                    {PROVIDER_LABELS[p].label}
                  </Badge>
                ))}
              </div>

              {/* Stats row */}
              <div className="flex items-center gap-3 text-[10px] text-muted-foreground">
                <span className="flex items-center gap-1">
                  <Shield className="h-3 w-3" /> {entry.sloAvailability}%
                </span>
                <span className="flex items-center gap-1">
                  <Clock className="h-3 w-3" /> ~{entry.estimatedDeployMin}m
                </span>
                <span className="flex items-center gap-1">
                  <DollarSign className="h-3 w-3" /> {entry.estimatedMonthlyCost}
                </span>
                <span className={`ml-auto text-[9px] font-mono ${STATUS_COLORS[entry.status]}`}>
                  {entry.status}
                </span>
              </div>

              {/* Preflight summary */}
              <div className="flex items-center gap-1 text-[9px] text-muted-foreground">
                <span className="uppercase tracking-wider font-semibold">Preflight:</span>
                {entry.preflightSteps.map((step) => (
                  <Badge key={step.id} variant="secondary" className="text-[8px] font-mono px-1.5 py-0">
                    {step.id}
                  </Badge>
                ))}
              </div>

              {/* Deploy buttons per provider */}
              <div className="flex items-center gap-2 pt-1">
                {entry.providers.map((p) => (
                  <Button
                    key={p}
                    size="sm"
                    variant="outline"
                    className="flex-1 text-[10px] h-7 gap-1 hover:bg-primary/10 hover:text-primary hover:border-primary/40"
                    onClick={() => onSelect(entry, p)}
                  >
                    <Cloud className="h-3 w-3" />
                    Deploy → {PROVIDER_LABELS[p].label}
                  </Button>
                ))}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {filtered.length === 0 && (
        <div className="text-center py-12 text-muted-foreground">
          <Layers className="h-8 w-8 mx-auto mb-2 opacity-40" />
          <p className="text-sm">No golden paths match your filters.</p>
        </div>
      )}
    </div>
  );
}

export { CATALOG };
